name: release

on:
  push:
    tags:
      - '*'
      
env:
  DOCKER_IMAGE: chuhlomin/genblog

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag
        id: tag
        run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.value }}
